CREATE TABLE `NOTEPADS` (
`ID` INT UNSIGNED NOT NULL,
`TITLE` VARCHAR(255) NOT NULL,
`SUBTITLE` VARCHAR(255) NOT NULL,
`CONTENT` TEXT NOT NULL,
PRIMARY KEY (ID)
)
;

ALTER TABLE notepads MODIFY COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT;

INSERT INTO notepads (title, subtitle, content) VALUES ('Titulo 2', 'Subtitulo 2', 'Conteúdo 2');

ALTER TABLE notepads ADD `created_at` timestamp DEFAULT CURRENT_TIMESTAMP;