CREATE TABLE `NOTEPADS` (
`ID` INT UNSIGNED NOT NULL,
`TITLE` VARCHAR(255) NOT NULL,
`SUBTITLE` VARCHAR(255) NOT NULL,
`CONTENT` TEXT NOT NULL,
PRIMARY KEY (ID)
)
;

ALTER TABLE notepads MODIFY COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT;

INSERT INTO notepads (title, subtitle, content) VALUES ('Titulo 2', 'Subtitulo 2', 'Conteúdo 2') RETURNING *;

ALTER TABLE notepads ADD `created_at` timestamp DEFAULT CURRENT_TIMESTAMP;

DELETE FROM notepads WHERE id = 1;

UPDATE notepads
SET 
title = ?,
subtitle = ?,
content = ?
WHERE id = ?;

CREATE TABLE posts AS SELECT * FROM notepads;

ALTER TABLE posts DROP COLUMN title, DROP COLUMN subtitle;

ALTER TABLE posts MODIFY id INT AUTO_INCREMENT;
ALTER TABLE posts ADD PRIMARY KEY (id);

CREATE TABLE comments (
id INT,
message TEXT NOT NULL, 
created_at TIMESTAMP,
post_id INT NOT NULL
)

ALTER TABLE comments ADD PRIMARY KEY (id);
ALTER TABLE comments MODIFY id INT AUTO_INCREMENT;
ALTER TABLE comments MODIFY created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE comments ADD CONSTRAINT FK_comments_post FOREIGN KEY (post_id) REFERENCES posts (id);